services:
  otel:
    image: grafana/otel-lgtm
    container_name: otel
    ports:
      - 3000:3000
      - 4317:4317
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: false
      GF_PATHS_DATA: /data/grafana
      GF_SECURITY_ADMIN_USER: ${OTEL_LGTM_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${OTEL_LGTM_ADMIN_PASSWORD}

    volumes:
      - grafana-data:/data/grafana  # Volume nomeado para Grafana
      - prometheus-data:/data/prometheus  # Volume nomeado para Prometheus
      - loki-data:/loki
      - ./conf/grafana/dashboard.yaml:/otel-lgtm/grafana/conf/provisioning/dashboards/grafana-dashboards.yaml
      - ./conf/grafana/opentelemetry-apm.json:/otel-lgtm/opentelemetry-apm.json
  
  volumes:
    pg-data:
    grafana-data:
    prometheus-data:
    loki-data:
