repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.13.0
  hooks:
    # Run the linter.
    - id: ruff-check
    # Run the formatter.
    - id: ruff-format
      args: [ --check, --diff ]

- repo: https://github.com/editorconfig-checker/editorconfig-checker
  # this git tag name is kept in sync by release-please
  rev: v3.2.0
  hooks:
    - id: editorconfig-checker
      stages:
        - pre-commit
